name: Pipeline JavaScript

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  executar-testes:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código do repositório
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Verificar versão do Node
        run: node --version

      - name: Executar arquivo JavaScript
        run: node login.js